name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('dev-requirements.txt') }}
    - name: Install dependencies
      run: pip install -r dev-requirements.txt
    - name: Run tests
      run: bash ./scripts/test.sh
    - name: Run
      run: |
        bash ./scripts/run.sh starfish/example-redirects.yml /tmp/Caddyfile
        cat /tmp/Caddyfile
